version: v1.0.0
date: 01-04-2024

server:
  port: 8087
  servlet:
    context-path: /dfg

management:
  server:
    port: 9889

spring:
  application:
    name: dynamic-pdf-generator
  datasource:
    oms-ds:
      url: jdbc:postgresql://localhost:5432/orders_db?currentSchema=purchase_order_LOCAL
      jdbcUrl: ${spring.datasource.oms-ds.url}
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: off
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false



